<?php

namespace Database\Seeders;

use App\Models\Tags;
use Arr;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    public function run()
    {
        $tags = [
            [
                'tag_id'     => '509660',
                'tag'        => 'Art',
                'tag_safe'   => 'art',
                'is_category'=> true,
            ],
            [
                'tag_id'     => '509661',
                'tag'        => 'Beauty & Body Art',
                'tag_safe'   => 'beauty-body-art',
                'is_category'=> true,
            ],
            [
                'tag_id'     => '488191',
                'tag'        => 'Creative',
                'tag_safe'   => 'creative',
                'is_category'=> true,
            ],
            [
                'tag_id'     => '509662',
                'tag'        => 'Food & Drink',
                'tag_safe'   => 'food-drink',
                'is_category'=> true,
            ],
            [
                'tag_id'     => '509673',
                'tag'        => 'Makers & Crafting',
                'tag_safe'   => 'makers-crafting',
                'is_category'=> true,
            ],
            [
                'tag_id'     => '26936',
                'tag'        => 'Music & Performing Arts',
                'tag_safe'   => 'music-performing-arts',

                'is_category'=> true,
            ],
            [
                'tag_id'     => '509670',
                'tag'        => 'Science & Technology',
                'tag_safe'   => 'science-technology',
                'is_category'=> true,
            ],
            [
                'tag_id'     => '417752',
                'tag'        => 'Talk Shows & Podcasts',
                'tag_safe'   => 'talk-shows-podcasts',
                'is_category'=> true,
            ],
            [
                'tag_id'     => '9166ad14-41f1-4b04-a3b8-c8eb838c6be6',
                'tag'        => 'German',
                'tag_safe'   => 'german',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e525f885-ccc0-42dd-9b6e-0586f76fdb3c',
                'tag'        => 'World Music',
                'tag_safe'   => 'world-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '9f1b01a8-87b9-4e25-94de-8705c1c1f4dc',
                'tag'        => 'Dance Music',
                'tag_safe'   => 'dance-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e590393c-084e-42d4-ae17-e15c9158b0e8',
                'tag'        => 'Mode: Creative',
                'tag_safe'   => 'mode-creative',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e659959d-392f-44c5-83a5-fb959cdbaccc',
                'tag'        => '100%',
                'tag_safe'   => '100',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6ea6bca4-4712-4ab9-a906-e3336a9d8039',
                'tag'        => 'English',
                'tag_safe'   => 'english',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd4bb9c58-2141-4881-bcdc-3fe0505457d1',
                'tag'        => 'Spanish',
                'tag_safe'   => 'spanish',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c2839af5-f1d2-46c4-8edc-1d0bfbd85070',
                'tag'        => 'Hype Train',
                'tag_safe'   => 'hype-train',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '049c2888-172c-4b36-a964-cdfad1051604',
                'tag'        => 'Composing',
                'tag_safe'   => 'composing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '325f7a22-26f4-4ad7-be48-f464de0b89ce',
                'tag'        => 'Musician',
                'tag_safe'   => 'musician',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c5247b10-deec-4d7a-84a5-db6a75cb5908',
                'tag'        => 'Music Events',
                'tag_safe'   => 'music-events',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6606e54c-f92d-40f6-8257-74977889ccdd',
                'tag'        => 'Anime',
                'tag_safe'   => 'anime',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e90b5f6e-4c6e-4003-885b-4d0d5adeb580',
                'tag'        => 'Family Friendly',
                'tag_safe'   => 'family-friendly',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2068d8f3-269c-43f2-9a00-82aeb3f0a3b8',
                'tag'        => 'Festival',
                'tag_safe'   => 'festival',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '338d7a92-8bcc-429e-a30c-9f1c41a2d79a',
                'tag'        => 'Electronic Music',
                'tag_safe'   => 'electronic-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3dc8f084-d886-4264-b20f-8bd5f90562b5',
                'tag'        => 'Animals',
                'tag_safe'   => 'animals',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b97ee881-e15a-455d-9876-657fcba7cfd8',
                'tag'        => '3D Modeling',
                'tag_safe'   => '3d-modeling',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6803fe7e-4e3d-4369-a8ae-1dc2afb758f9',
                'tag'        => '3D Printing',
                'tag_safe'   => '3d-printing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a59f1e4e-257b-4bd0-90c7-189c3efbf917',
                'tag'        => 'Programming',
                'tag_safe'   => 'programming',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8a01ea18-df97-4046-9cff-a9a822bb96e5',
                'tag'        => 'Closed Captions',
                'tag_safe'   => 'closed-captions',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0569b171-2a2b-476e-a596-5bdfb45a1327',
                'tag'        => 'Russian',
                'tag_safe'   => 'russian',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ab2975e3-b9ca-4b1a-a93e-fb61a5d5c3a4',
                'tag'        => 'Korean',
                'tag_safe'   => 'korean',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ddb625af-5920-49cc-9f13-3716f87941dc',
                'tag'        => 'Music Production',
                'tag_safe'   => 'music-production',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8c1ada77-52f0-4935-a1b0-a02dc65f28b4',
                'tag'        => 'Singing',
                'tag_safe'   => 'singing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '19320835-e4e5-4561-9105-3517abd87879',
                'tag'        => 'Rap',
                'tag_safe'   => 'rap',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ffc3eb89-13e8-45cb-907f-4d9eb8f32d43',
                'tag'        => 'Radio',
                'tag_safe'   => 'radio',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5f0c32b8-2bdf-47e2-ae63-9abc2fe61776',
                'tag'        => 'Hip Hop',
                'tag_safe'   => 'hip-hop',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6497804e-494c-427d-8e96-30da54e7b4ec',
                'tag'        => 'Reggae',
                'tag_safe'   => 'reggae',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'bfa85d5d-28f2-4faa-81ac-9fa8995fe188',
                'tag'        => 'R&B',
                'tag_safe'   => 'rb',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '55afc9b3-67c9-46a0-aaad-d2fc65202f1b',
                'tag'        => 'House',
                'tag_safe'   => 'house',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '220eb274-ab25-425b-8a9b-826103404997',
                'tag'        => 'Finnish',
                'tag_safe'   => 'finnish',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e46ae70e-40a4-4b00-a1f3-a2f79721d1f6',
                'tag'        => 'Indie Music',
                'tag_safe'   => 'indie-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '744f1c0b-458e-4a12-a759-bfa2edb7c81a',
                'tag'        => 'Pop',
                'tag_safe'   => 'pop',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '938fcad2-4d77-4a06-9e49-b75b0879b645',
                'tag'        => 'Metal Music',
                'tag_safe'   => 'metal-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '60c39042-60b6-49b9-8132-cf720b79c5bf',
                'tag'        => 'Soul Music',
                'tag_safe'   => 'soul-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f27da80e-b26a-447b-bcfa-b20ac049d333',
                'tag'        => 'Rock',
                'tag_safe'   => 'rock',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '57e81aba-c8ae-48aa-8fba-7a7eb9d3dd23',
                'tag'        => 'Alternative Music',
                'tag_safe'   => 'alternative-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'eea4d45b-52e0-4a16-b0df-64f4c55bc716',
                'tag'        => 'Acoustic',
                'tag_safe'   => 'acoustic',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ba8a733b-9721-4980-812b-e40da19e860a',
                'tag'        => 'Original Work',
                'tag_safe'   => 'original-work',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'cea7bc0c-75a5-4446-8743-6db031b71550',
                'tag'        => 'Educational',
                'tag_safe'   => 'educational',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '39ee8140-901a-4762-bfca-8260dea1310f',
                'tag'        => 'Portuguese',
                'tag_safe'   => 'portuguese',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f08d5873-f0c7-4912-94ba-a41933b4c141',
                'tag'        => 'Turkish',
                'tag_safe'   => 'turkish',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6ba1d230-e52f-4d81-b1e0-41f25a8a9f5d',
                'tag'        => 'Japanese',
                'tag_safe'   => 'japanese',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '67259b26-ff83-444e-9d3c-faab390df16f',
                'tag'        => 'AMA',
                'tag_safe'   => 'ama',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e027fb8b-219e-4959-8240-a4a082be0316',
                'tag'        => 'Retro',
                'tag_safe'   => 'retro',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8bbdb07d-df18-4f82-a928-04a9003e9a7e',
                'tag'        => 'LGBTQIA+',
                'tag_safe'   => 'lgbtqia',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e3a6b378-232b-4ec2-9a82-86b72851e09a',
                'tag'        => 'Animation',
                'tag_safe'   => 'animation',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '85d2fb8f-7257-4e08-8065-6161fa3029fa',
                'tag'        => 'Music Talk',
                'tag_safe'   => 'music-talk',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '77223888-8535-4614-974b-b1b2673456eb',
                'tag'        => 'Visual ASMR',
                'tag_safe'   => 'visual-asmr',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '9801169b-afa4-4785-890e-53911955e4d7',
                'tag'        => 'Mindfulness',
                'tag_safe'   => 'mindfulness',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '589c4c39-a3cc-41fa-b70c-bf0b735fa21f',
                'tag'        => 'Mental Health',
                'tag_safe'   => 'mental-health',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '44edf4da-f267-40e3-b6c8-0a21bcee4ba7',
                'tag'        => 'Theater',
                'tag_safe'   => 'theater',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a1732569-de54-4b75-8a17-07744179f6d9',
                'tag'        => 'KR Server',
                'tag_safe'   => 'kr-server',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b6b64b15-447c-4178-9609-d3d511123521',
                'tag'        => 'K-Pop',
                'tag_safe'   => 'k-pop',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '60b8f13e-7022-481a-afff-07de3db129cc',
                'tag'        => 'Classical',
                'tag_safe'   => 'classical',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd6bf03b8-42f4-4981-b070-841c7457a9aa',
                'tag'        => 'Improv',
                'tag_safe'   => 'improv',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '54854b39-5f23-4ff2-b6a6-de0d2ff65107',
                'tag'        => 'Miniature Figures',
                'tag_safe'   => 'miniature-figures',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5ec52c4f-a055-404c-82fe-ea98c74c7fe6',
                'tag'        => 'Traditional Art',
                'tag_safe'   => 'traditional-art',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1d3d4f9c-be88-44f3-8e80-3b0779308c64',
                'tag'        => 'Painting',
                'tag_safe'   => 'painting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '74c92063-a389-4fd2-8460-b1bb82b04ec7',
                'tag'        => 'Chinese',
                'tag_safe'   => 'chinese',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6f655045-9989-4ef7-8f85-1edcec42d648',
                'tag'        => 'French',
                'tag_safe'   => 'french',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c23ce252-cf78-4b98-8c11-8769801aaf3a',
                'tag'        => 'Web Development',
                'tag_safe'   => 'web-development',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6f86127d-6051-4a38-94bb-f7b475dde109',
                'tag'        => 'Software Development',
                'tag_safe'   => 'software-development',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f588bd74-e496-4d11-9169-3597f38a5d25',
                'tag'        => 'Game Development',
                'tag_safe'   => 'game-development',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '02ba4017-ed3b-4b82-ab20-011860784f77',
                'tag'        => 'Digital Art',
                'tag_safe'   => 'digital-art',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '9ba743f4-85e4-40e2-a83c-c5b24aab797b',
                'tag'        => 'Emote Design',
                'tag_safe'   => 'emote-design',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f2d10665-9980-452a-b091-f0ca30777d4b',
                'tag'        => 'Drawing',
                'tag_safe'   => 'drawing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'df448da8-7082-45b2-92ad-c624dba6551f',
                'tag'        => 'Art Commissions',
                'tag_safe'   => 'art-commissions',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '64d9afa6-139a-48d5-ab4e-51d0a92b22de',
                'tag'        => 'Auditory ASMR',
                'tag_safe'   => 'auditory-asmr',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'fd76c790-0505-4c4c-865a-d6bd139c0901',
                'tag'        => 'Language: Other',
                'tag_safe'   => 'language-other',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'dfaa4f24-e99f-430d-aa29-8fb2b2717ece',
                'tag'        => 'Illustration',
                'tag_safe'   => 'illustration',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '7b49f69a-5d95-4c94-b7e3-66e2c0c6f6c6',
                'tag'        => 'Design',
                'tag_safe'   => 'design',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '86bd38a4-8ef9-4e4a-892f-f4d0aa336d67',
                'tag'        => 'Fan Art',
                'tag_safe'   => 'fan-art',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '04b4aaaa-c410-4c2e-9beb-da3896fc7d22',
                'tag'        => 'Practice',
                'tag_safe'   => 'practice',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0cef8341-8c67-481f-95a8-325932a6699c',
                'tag'        => 'Evil Characters',
                'tag_safe'   => 'evil-characters',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ba2c968b-867a-49ce-aebc-3d978a204f4a',
                'tag'        => 'Hard Mode',
                'tag_safe'   => 'hard-mode',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '4042b087-9c79-4358-8c99-b3c25e7deaa7',
                'tag'        => 'Funk',
                'tag_safe'   => 'funk',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3c0a4e1f-6863-4dad-bb4e-538326306bef',
                'tag'        => 'Pixel Art',
                'tag_safe'   => 'pixel-art',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1706e401-a023-49fc-9b10-7bf73f59c940',
                'tag'        => 'Marathon',
                'tag_safe'   => 'marathon',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'bb5e7234-380e-48ad-a59c-03e51274e478',
                'tag'        => 'Charity',
                'tag_safe'   => 'charity',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ff56eeeb-99ed-4a60-93fc-0b3f05d8661e',
                'tag'        => 'Multiplayer',
                'tag_safe'   => 'multiplayer',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1eba3cfe-51cc-460a-8259-bc8bb987f904',
                'tag'        => 'Competitive',
                'tag_safe'   => 'competitive',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '22c54bdc-2637-4612-9a9f-883b33b9f69d',
                'tag'        => 'Folk',
                'tag_safe'   => 'folk',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'bd6fc011-575a-43f0-8418-9f912a295362',
                'tag'        => 'Reading Aloud',
                'tag_safe'   => 'reading-aloud',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '06ab147d-91b6-4c7f-83e4-2b337d2780d5',
                'tag'        => 'Voice Acting',
                'tag_safe'   => 'voice-acting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '81975ba3-5c53-41f8-b614-ce5b3193955a',
                'tag'        => 'Writing',
                'tag_safe'   => 'writing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ce8e38a5-bd6b-4bab-b671-d7144d85b266',
                'tag'        => 'Raid Content',
                'tag_safe'   => 'raid-content',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e844c795-5128-4ca0-a950-f64dabf5a324',
                'tag'        => 'Sculpture',
                'tag_safe'   => 'sculpture',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2ffd5c3e-b927-4749-ba53-79d3b626b2da',
                'tag'        => 'Cosplay',
                'tag_safe'   => 'cosplay',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '43e598cc-918b-4247-b02c-b13543a1eac9',
                'tag'        => 'Danish',
                'tag_safe'   => 'danish',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '85a78d1f-77e7-468e-a3e5-76ed7c99864b',
                'tag'        => 'Level Design',
                'tag_safe'   => 'level-design',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '319e29b7-9b61-4f0b-ad11-43e4c01ca697',
                'tag'        => 'Coloring',
                'tag_safe'   => 'coloring',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c38aeb6e-e8c7-452a-88e1-a3ed62c2e846',
                'tag'        => 'Business',
                'tag_safe'   => 'business',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ef4f33d5-a6cb-4935-bc1d-97c818a1e39e',
                'tag'        => 'Analysis',
                'tag_safe'   => 'analysis',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0b122d41-1e9b-4086-9a42-1e7db94f1bd1',
                'tag'        => 'Sewing',
                'tag_safe'   => 'sewing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2920fbf2-293e-4753-8ec7-b69dba5392d0',
                'tag'        => 'Warming Up',
                'tag_safe'   => 'warming-up',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3379ff9c-3c15-4bef-bfb8-2085cd196062',
                'tag'        => 'Endurance Training',
                'tag_safe'   => 'endurance-training',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f9d04efa-6e25-49bf-bf0a-da3e2addaf1b',
                'tag'        => 'Polish',
                'tag_safe'   => 'polish',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a6cddaba-f0ce-4526-9087-6de2f603a24d',
                'tag'        => 'Czech',
                'tag_safe'   => 'czech',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3280c8d8-64c0-45f7-aeaa-189928b0e82c',
                'tag'        => 'FGC',
                'tag_safe'   => 'fgc',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'dc709206-c072-4340-a706-694578574c7e',
                'tag'        => 'Tutorial',
                'tag_safe'   => 'tutorial',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0930677c-dd75-424d-9190-b779f3d1c136',
                'tag'        => 'Graphic Design',
                'tag_safe'   => 'graphic-design',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '9d0e6082-403a-4693-b3a9-cc7de4c84866',
                'tag'        => 'Instrumental',
                'tag_safe'   => 'instrumental',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8282259b-a997-4c63-b908-24027f64ac9a',
                'tag'        => 'Solos',
                'tag_safe'   => 'solos',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5b9935eb-1e9a-4217-98ad-62bda5cff0d1',
                'tag'        => 'Italian',
                'tag_safe'   => 'italian',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0cfc77a1-9f3f-4858-8847-4b00c7a9aa8b',
                'tag'        => 'Pop Culture',
                'tag_safe'   => 'pop-culture',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b547f13b-4b4b-460f-97e6-3af350356a69',
                'tag'        => 'Ukrainian',
                'tag_safe'   => 'ukrainian',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'bfedff64-c53a-4e6f-bda4-9eeb36dc8853',
                'tag'        => 'Unreal Engine',
                'tag_safe'   => 'unreal-engine',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '69318d09-f132-4853-b4b6-09a0580f7092',
                'tag'        => 'No Backseating',
                'tag_safe'   => 'no-backseating',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '62bc5436-6f91-446d-9651-da008da4e4bb',
                'tag'        => 'Coaching',
                'tag_safe'   => 'coaching',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ac763b17-7bea-4632-9eb4-d106689ff409',
                'tag'        => 'Playing with Viewers',
                'tag_safe'   => 'playing-with-viewers',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '89e105c9-2c45-42a9-a5f0-fc1ea6e7ba8b',
                'tag'        => 'Outdoors',
                'tag_safe'   => 'outdoors',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a298cca5-d408-47c7-a1e7-0c76ca878bc6',
                'tag'        => 'Hungarian',
                'tag_safe'   => 'hungarian',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ea24c3ca-c351-4c6c-af02-2c44ef769d97',
                'tag'        => 'Scale Modeling',
                'tag_safe'   => 'scale-modeling',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'dbe20395-0e44-4156-92de-4a77f6cdccf0',
                'tag'        => 'Wargame',
                'tag_safe'   => 'wargame',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '56257f86-a66c-4ce8-af6d-89e9b1f13fed',
                'tag'        => 'Robotics',
                'tag_safe'   => 'robotics',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'cb00cfe5-ae4e-4e4f-a8f1-8fa6ddec6361',
                'tag'        => 'Fantasy Sports',
                'tag_safe'   => 'fantasy-sports',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e6be5e22-30e0-4b34-89f1-092564cc8462',
                'tag'        => 'Latin Music',
                'tag_safe'   => 'latin-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ad18ee82-c0b2-46d4-b4f9-d45994443bd7',
                'tag'        => 'Beginner Players',
                'tag_safe'   => 'beginner-players',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '48f31aeb-6f50-4c78-a13d-b9bb47a8b745',
                'tag'        => 'Contemporary Dance',
                'tag_safe'   => 'contemporary-dance',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '7a3d677a-1e09-4391-b520-1fccc0e7d6ca',
                'tag'        => 'Live Vlogging',
                'tag_safe'   => 'live-vlogging',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ffc2deb9-cdac-4d5a-8554-381f165805ca',
                'tag'        => 'Mixed Reality',
                'tag_safe'   => 'mixed-reality',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1d712738-c298-4ff9-9c15-671ae9a77b7c',
                'tag'        => 'Comics',
                'tag_safe'   => 'comics',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f1e3759c-35b3-4858-a50f-8f9cafc2660f',
                'tag'        => 'Brickbuilding',
                'tag_safe'   => 'brickbuilding',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e3c42c93-376e-4e8e-aa5d-c4e06a765416',
                'tag'        => 'Photography',
                'tag_safe'   => 'photography',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8ba227ca-073c-46a7-b3cc-193e52c5ab4d',
                'tag'        => "Let's Play",
                'tag_safe'   => 'lets-play',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '21d85c73-701f-4259-8c4e-4321265847b5',
                'tag'        => 'Bulgarian',
                'tag_safe'   => 'bulgarian',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '292d76d1-b0a2-4175-a313-fdb2c970cd69',
                'tag'        => 'Mode: Survival',
                'tag_safe'   => 'mode-survival',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5e798958-88a4-474a-bd7f-07178a0def0c',
                'tag'        => 'Character Creation',
                'tag_safe'   => 'character-creation',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '50a54ea7-c9f5-4b59-8056-32f10b0d6983',
                'tag'        => 'Inking',
                'tag_safe'   => 'inking',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b92810f0-0d48-4be6-90a3-766e53353ed7',
                'tag'        => 'Papercraft',
                'tag_safe'   => 'papercraft',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ca470745-c1df-4c11-9474-9ab79dfc1863',
                'tag'        => 'VR',
                'tag_safe'   => 'vr',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6e23d976-33ec-47e8-b22b-3727acd41862',
                'tag'        => 'Mobile Development',
                'tag_safe'   => 'mobile-development',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2b2a4874-8a3c-4995-b9e2-2a0bce1eb536',
                'tag'        => 'Squads',
                'tag_safe'   => 'squads',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'fd8f5e68-42d3-4544-a273-5fc92dabc568',
                'tag'        => 'Mode: Battle Royale',
                'tag_safe'   => 'mode-battle-royale',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '55d222b4-0620-4791-97c5-e15b021bda63',
                'tag'        => 'Tattooing',
                'tag_safe'   => 'tattooing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e13e6734-37ae-4d85-897b-3015f0168355',
                'tag'        => 'Dutch',
                'tag_safe'   => 'dutch',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '75a99c80-0f15-4159-b1fd-3812c25b4aca',
                'tag'        => 'Romanian',
                'tag_safe'   => 'romanian',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'dcf598ca-b5de-47d4-af33-ecabe9eaeee1',
                'tag'        => 'EU Server',
                'tag_safe'   => 'eu-server',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'cc8d5abb-39c9-4942-a1ee-e1558512119e',
                'tag'        => 'Casual Playthrough',
                'tag_safe'   => 'casual-playthrough',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c9193f35-a88f-4f03-af99-b73fe0db60f3',
                'tag'        => 'Any%',
                'tag_safe'   => 'any',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0c8c6543-4019-47d0-9b8a-57a81ee6ace5',
                'tag'        => 'Chinese (Cantonese)',
                'tag_safe'   => 'chinese-cantonese',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8b1246f2-2cec-4b90-9d86-01ebdf13b848',
                'tag'        => 'Indonesian',
                'tag_safe'   => 'indonesian',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e2eab38e-8ce7-4b97-baaf-5f8e2296bfdd',
                'tag'        => 'Hip Hop Dance',
                'tag_safe'   => 'hip-hop-dance',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '36b47e6e-6cdf-46fa-a85e-bd18a64af7ad',
                'tag'        => 'Mode: Adventure',
                'tag_safe'   => 'mode-adventure',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '13c95a9e-a17d-4225-b199-d08cb8e66f40',
                'tag'        => 'Party Game',
                'tag_safe'   => 'party-game',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd0976a7e-26a7-4a48-9225-c522808540f2',
                'tag'        => 'First Playthrough',
                'tag_safe'   => 'first-playthrough',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '96b6073f-450d-4248-8ed4-988e28f3f759',
                'tag'        => 'Backseating Allowed',
                'tag_safe'   => 'backseating-allowed',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2892b8a9-5234-4de1-a575-9d7b00401f64',
                'tag'        => 'Jazz',
                'tag_safe'   => 'jazz',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '26bb14e0-0b3e-4f7c-9701-16367b6d55e3',
                'tag'        => 'Blues',
                'tag_safe'   => 'blues',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8d131cac-82f2-4bc8-8a78-9c7aa045f4e2',
                'tag'        => 'Punk Music',
                'tag_safe'   => 'punk-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c48e0bf4-7a1b-4ffd-893c-12e46e664f7f',
                'tag'        => 'Game Jam',
                'tag_safe'   => 'game-jam',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c0bfabb1-0a43-41a8-8f6c-c7c434ca18f9',
                'tag'        => 'Woodwork',
                'tag_safe'   => 'woodwork',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f0ab2b07-14ed-4429-8ea3-3d7d400a50cd',
                'tag'        => 'Vector Art',
                'tag_safe'   => 'vector-art',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3ffbec21-97a2-43f9-bd73-4506a1b4d62c',
                'tag'        => 'Farming',
                'tag_safe'   => 'farming',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '325a32c7-7b8e-48f8-b4fa-10875f18bb6d',
                'tag'        => 'Editing',
                'tag_safe'   => 'editing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e22ac23e-c640-498b-b6a0-6e2009735497',
                'tag'        => 'Photo Mode',
                'tag_safe'   => 'photo-mode',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1e95d7b4-8dac-4b5f-81d5-f963fdc5d989',
                'tag'        => 'Leatherwork',
                'tag_safe'   => 'leatherwork',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e85e4ccb-41fa-45b4-9c3a-f37807af3a5a',
                'tag'        => 'League',
                'tag_safe'   => 'league',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2e037750-5051-44ea-a51f-7a376bbacb29',
                'tag'        => 'Duos',
                'tag_safe'   => 'duos',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '26befb18-4ddc-41c1-8d39-ffeada297428',
                'tag'        => 'Behind the Scenes',
                'tag_safe'   => 'behind-the-scenes',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c50b4290-44da-4f41-94bd-1a64325aab08',
                'tag'        => 'Crocheting',
                'tag_safe'   => 'crocheting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f19c7524-c18d-41af-9f39-034c8d0b0fee',
                'tag'        => 'Thai',
                'tag_safe'   => 'thai',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1e399a95-33f1-47c6-9511-adfb1d72a61a',
                'tag'        => 'Convention',
                'tag_safe'   => 'convention',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '90cde8f1-1372-4c65-baac-0eb888c098bc',
                'tag'        => 'Draft',
                'tag_safe'   => 'draft',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a6ff589a-33e5-4caf-8286-29dea98fc2e2',
                'tag'        => 'Travel',
                'tag_safe'   => 'travel',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f7c66388-34d7-4ac7-b171-b6a18053cae9',
                'tag'        => 'Downtempo',
                'tag_safe'   => 'downtempo',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '4d580385-6b91-4cee-aedf-0d79ea956694',
                'tag'        => 'Dubstep',
                'tag_safe'   => 'dubstep',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e1a43486-eee5-4f36-9ee6-76e72af00180',
                'tag'        => 'Ranked',
                'tag_safe'   => 'ranked',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd6de2e71-689a-4c47-ad61-6ec6182f9491',
                'tag'        => 'Glitch Hunting',
                'tag_safe'   => 'glitch-hunting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'db2a18b3-3800-4949-9454-4ef1851b9895',
                'tag'        => 'Fishing',
                'tag_safe'   => 'fishing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd4461e94-570b-4973-b6a1-3afe026c12ca',
                'tag'        => 'Social Eating',
                'tag_safe'   => 'social-eating',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '902f6815-a655-4918-99e7-48c74a71feac',
                'tag'        => 'Greek',
                'tag_safe'   => 'greek',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '572bbbbc-ab94-4cbd-8c1f-649d856267b5',
                'tag'        => 'Cross-Stitch',
                'tag_safe'   => 'cross-stitch',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '145b073b-cb70-4e91-b170-f5fab2ebba05',
                'tag'        => 'Swedish',
                'tag_safe'   => 'swedish',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '396aee63-bb8a-43c4-95da-98fca08e144b',
                'tag'        => 'Standup Comedy',
                'tag_safe'   => 'standup-comedy',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a31daeb5-edc2-4b29-afa1-84c96612836d',
                'tag'        => '12 Hour Challenge',
                'tag_safe'   => '12-hour-challenge',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'adb55316-f1ab-4f81-9ff5-17da7719d0ee',
                'tag'        => 'Co-Stream',
                'tag_safe'   => 'co-stream',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '69b5f1ed-6224-49c2-8c87-708fe3850f0a',
                'tag'        => 'Gardening',
                'tag_safe'   => 'gardening',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c833db83-32d0-4026-b3df-637ccf7899fa',
                'tag'        => 'Interviews',
                'tag_safe'   => 'interviews',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '77017b7b-6b98-4f0d-bd39-3ba96b66ec7a',
                'tag'        => 'News',
                'tag_safe'   => 'news',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '26301bb2-91a3-4272-8a9b-5bcea6db0fcd',
                'tag'        => 'Singleplayer',
                'tag_safe'   => 'singleplayer',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '79dc53e2-32d1-4e6b-8276-22102c150c1b',
                'tag'        => 'Fiber Arts',
                'tag_safe'   => 'fiber-arts',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6ec0d7d3-594f-49a1-a86f-34e9b920621d',
                'tag'        => 'Knitting',
                'tag_safe'   => 'knitting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2fd30cb8-f2e5-415d-9d42-1316cfa61367',
                'tag'        => 'Randomizer',
                'tag_safe'   => 'randomizer',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c67e3f4d-200f-4f75-a836-0420616054a7',
                'tag'        => 'NG+',
                'tag_safe'   => 'ng',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '76e1d57a-8bce-4f05-95df-02fd1e536fef',
                'tag'        => 'Roll and Move',
                'tag_safe'   => 'roll-and-move',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0cb7e377-a308-44e8-91f7-07eea1d96129',
                'tag'        => 'Roleplay',
                'tag_safe'   => 'roleplay',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '73cc486a-e56b-41ed-a1df-7afedbc84f6f',
                'tag'        => 'Arabic',
                'tag_safe'   => 'arabic',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'dff0aca6-52fe-4cc4-a93a-194852b522f0',
                'tag'        => 'Engineering',
                'tag_safe'   => 'engineering',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '246d6e4b-b9c6-442b-9573-77028839f194',
                'tag'        => 'Fashion',
                'tag_safe'   => 'fashion',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '63e83904-a70b-4709-b963-a37a105d9932',
                'tag'        => 'Cooperative',
                'tag_safe'   => 'cooperative',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f8629a4c-ecce-4eca-b8fe-31838605102c',
                'tag'        => 'Shopping',
                'tag_safe'   => 'shopping',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3ef3258b-5623-41da-8f5f-169c716a84da',
                'tag'        => 'Extra Life',
                'tag_safe'   => 'extra-life',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ebb68e1c-7291-4350-a8f4-44b484f1da2f',
                'tag'        => 'Country Music',
                'tag_safe'   => 'country-music',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f4b7fa12-9f16-439f-a6b9-87efe9ecf3ba',
                'tag'        => 'Gaming News',
                'tag_safe'   => 'gaming-news',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b3d8d789-dd4d-4566-8a9b-62a182ada7d5',
                'tag'        => 'PC Building',
                'tag_safe'   => 'pc-building',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'cd9ed640-426d-4a08-b8e0-417a61197264',
                'tag'        => 'Unboxing',
                'tag_safe'   => 'unboxing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '9b773670-05f8-4c06-ac99-e6649f906171',
                'tag'        => 'Slovak',
                'tag_safe'   => 'slovak',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '738d81a3-d79a-44a8-8351-b406d96b9cd9',
                'tag'        => 'Finance',
                'tag_safe'   => 'finance',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '79977fb9-f106-4a87-a386-f1b0f99783dd',
                'tag'        => 'PvE',
                'tag_safe'   => 'pve',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8486f56b-8677-44f7-8004-000295391524',
                'tag'        => 'PvP',
                'tag_safe'   => 'pvp',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '56d53a63-f048-40a9-ab61-d363aa3b9c57',
                'tag'        => 'Hindi',
                'tag_safe'   => 'hindi',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '812a0088-22a9-4944-bb27-af0fa37b6085',
                'tag'        => 'Filming',
                'tag_safe'   => 'filming',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6a0c6ea2-84eb-42b1-a8bb-59fd684bfe1a',
                'tag'        => 'Game Show',
                'tag_safe'   => 'game-show',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5464696d-e140-4625-94fd-1d0001e4b1ee',
                'tag'        => 'Fortune Telling',
                'tag_safe'   => 'fortune-telling',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8b3b089d-aae5-4a00-8d10-b01a28451b08',
                'tag'        => 'Weather',
                'tag_safe'   => 'weather',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '011f7c20-f533-4ad1-8093-8c6f8f75bc4c',
                'tag'        => 'Drag',
                'tag_safe'   => 'drag',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '7e2022f8-924e-4a2f-bd67-92e5c051dc95',
                'tag'        => 'History',
                'tag_safe'   => 'history',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6433db3e-37a7-4590-915a-7c0949a4ac69',
                'tag'        => 'Leveling',
                'tag_safe'   => 'leveling',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '60f44eae-0460-4cd4-b7cf-90567a031382',
                'tag'        => 'Mode: Zombies',
                'tag_safe'   => 'mode-zombies',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5647bf35-f99e-49aa-8578-0e07d936188c',
                'tag'        => 'Norwegian',
                'tag_safe'   => 'norwegian',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b76cb377-f766-48a7-b148-88bcb3932017',
                'tag'        => 'Plants',
                'tag_safe'   => 'plants',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '81df4005-f654-40b2-9fc0-9fd767bc8e3e',
                'tag'        => 'Challenge Run',
                'tag_safe'   => 'challenge-run',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '621fb5bf-5498-4d8f-b4ac-db4d40d401bf',
                'tag'        => '1 Credit Clear',
                'tag_safe'   => '1-credit-clear',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b638f288-a35b-4b46-921e-54f59612a844',
                'tag'        => 'No Limit',
                'tag_safe'   => 'no-limit',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'aa971bdc-a28d-4a33-a686-f112c764e73b',
                'tag'        => 'Drones',
                'tag_safe'   => 'drones',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '91d21edf-9d63-4ac8-9508-5448c3daf3f0',
                'tag'        => 'Tagalog',
                'tag_safe'   => 'tagalog',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ee1daaae-116a-44d6-9f40-09322caf3181',
                'tag'        => 'Good Characters',
                'tag_safe'   => 'good-characters',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'fec05015-e841-4cff-a53c-8aa1336cf863',
                'tag'        => 'Viewer Levels',
                'tag_safe'   => 'viewer-levels',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5ad4b978-495f-4093-9461-c194f58201ab',
                'tag'        => 'American Sign Language',
                'tag_safe'   => 'american-sign-language',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'fd6df368-7e76-4868-b9e9-b4f7cecc2f35',
                'tag'        => 'Skateboarding',
                'tag_safe'   => 'skateboarding',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '7ecdb5ae-e036-402e-8663-edc77167d6df',
                'tag'        => 'Mode: Campaign',
                'tag_safe'   => 'mode-campaign',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '42d950b3-e90f-4ef0-a22a-5e6a31d67ba5',
                'tag'        => 'Ceramics',
                'tag_safe'   => 'ceramics',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '10e94b3e-333b-413a-989e-35635210c127',
                'tag'        => 'Glasswork',
                'tag_safe'   => 'glasswork',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0074af4d-eb56-4e57-89b6-07c39c63c9c4',
                'tag'        => 'Spoilers',
                'tag_safe'   => 'spoilers',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'cee0e0bb-60b1-46a8-be53-ba46c05727b3',
                'tag'        => 'Metalwork',
                'tag_safe'   => 'metalwork',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b5cc71f3-4c4d-46ed-8041-2d5ecb525051',
                'tag'        => 'Mixology',
                'tag_safe'   => 'mixology',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1648d895-0548-4355-bdce-09c6fe3c4d21',
                'tag'        => 'Campaign Planning',
                'tag_safe'   => 'campaign-planning',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6c27ea04-fceb-4a13-8e5e-2c500432c7ff',
                'tag'        => 'Birthday',
                'tag_safe'   => 'birthday',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b0fe1976-afcd-4ea0-b55c-2d140cd2cd57',
                'tag'        => 'Quilting',
                'tag_safe'   => 'quilting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'eaba0ad7-c4e1-4878-b37f-01308dbb65c8',
                'tag'        => 'No Spoilers',
                'tag_safe'   => 'no-spoilers',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a5067bb9-0567-483b-88a6-7aa79985f272',
                'tag'        => 'No Damage',
                'tag_safe'   => 'no-damage',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e0bec521-5ff6-49cf-bea3-f01051c1da18',
                'tag'        => 'Skincare',
                'tag_safe'   => 'skincare',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5cf2121f-fff0-4375-84a7-4119d54a8b95',
                'tag'        => 'Dice',
                'tag_safe'   => 'dice',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ea731a85-fd78-4cce-ab94-c71b2d0f9fc7',
                'tag'        => 'Sit & Go',
                'tag_safe'   => 'sit-go',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c267da2b-097a-4d7d-bb34-4b08498ac1a4',
                'tag'        => 'Cooking',
                'tag_safe'   => 'cooking',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '52233ce2-9b31-4f67-8b39-12aea5df66bf',
                'tag'        => 'Makeup',
                'tag_safe'   => 'makeup',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c5be8a99-b55a-4388-a0ce-bf3468984100',
                'tag'        => 'Lettering',
                'tag_safe'   => 'lettering',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ab45fcb7-a22d-4a07-b0ac-fb3940566fa7',
                'tag'        => 'Meme Runs',
                'tag_safe'   => 'meme-runs',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '9458de4e-6d35-422a-84a9-f243a49c212e',
                'tag'        => 'Modded',
                'tag_safe'   => 'modded',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '7cefbf30-4c3e-4aa7-99cd-70aabb662f27',
                'tag'        => 'Speedrun',
                'tag_safe'   => 'speedrun',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2b19c8f9-695f-4ea1-a5fe-eba176770dbc',
                'tag'        => 'WR Attempts',
                'tag_safe'   => 'wr-attempts',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd557fc7d-23da-48aa-87a4-35877fd57646',
                'tag'        => 'Glitchless',
                'tag_safe'   => 'glitchless',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '7199189a-0569-4854-908e-08e6c3667379',
                'tag'        => 'Wrestling',
                'tag_safe'   => 'wrestling',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e03c93a4-74ae-4358-8b3c-8189e5a1fbec',
                'tag'        => 'Permadeath',
                'tag_safe'   => 'permadeath',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3ce58361-f147-441d-a7c9-e98e3e916a39',
                'tag'        => 'Meal Prep',
                'tag_safe'   => 'meal-prep',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6e5ed4f2-ea10-4245-82c5-55e4c128eccf',
                'tag'        => 'KeyCaps',
                'tag_safe'   => 'keycaps',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c9ee687c-e233-4e60-9a32-70eda37581c7',
                'tag'        => 'Basketball',
                'tag_safe'   => 'basketball',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '653ad792-5ec6-4bd9-aeb6-8a70b32f1ee4',
                'tag'        => 'Racing',
                'tag_safe'   => 'racing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f6dda089-56ef-4fb5-b06e-ddeba46fb5f2',
                'tag'        => 'Ballroom Dance',
                'tag_safe'   => 'ballroom-dance',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2e048a36-0e6a-4322-a16b-45dd0268c9bf',
                'tag'        => 'Blindfolded',
                'tag_safe'   => 'blindfolded',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0c091738-2e83-4293-be16-6a2a77200399',
                'tag'        => 'Brewing',
                'tag_safe'   => 'brewing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'aeab850d-94ec-4af5-89a0-9eb1bf41558d',
                'tag'        => 'End Game',
                'tag_safe'   => 'end-game',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'eeea68da-c4b8-4268-b17a-eb0f30286843',
                'tag'        => 'Cash Game',
                'tag_safe'   => 'cash-game',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '4ada413e-c7c4-4fc0-b3d6-ce4b98e0d5e3',
                'tag'        => 'Soccer',
                'tag_safe'   => 'soccer',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '89d8bfd0-0b87-468e-b24b-086b2d3cd3c8',
                'tag'        => 'Rockets',
                'tag_safe'   => 'rockets',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f317a85e-495e-4aee-a0d2-0720bd00a6ce',
                'tag'        => 'TwitchCon',
                'tag_safe'   => 'twitchcon',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '353ab6ac-a0ee-404e-9bfa-217446b97718',
                'tag'        => 'NA Server',
                'tag_safe'   => 'na-server',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e582533d-dc1f-46bc-a94b-ac316a779635',
                'tag'        => 'Perler',
                'tag_safe'   => 'perler',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '54107c64-4d7b-4235-bd1f-4da1ef3b5d64',
                'tag'        => 'Jewelry Making',
                'tag_safe'   => 'jewelry-making',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1400ca9c-84ea-414e-a85b-076a70d38ecf',
                'tag'        => 'Automotive',
                'tag_safe'   => 'automotive',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b2c03e34-e7c2-4fcd-939a-6853838edce5',
                'tag'        => 'Anniversary',
                'tag_safe'   => 'anniversary',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '987b6325-fb45-40a4-a710-32b86221a06c',
                'tag'        => 'Pyrography',
                'tag_safe'   => 'pyrography',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1a60fb07-26d0-450d-b777-f5414baabc28',
                'tag'        => 'Gen Con',
                'tag_safe'   => 'gen-con',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd11b9289-806a-403b-945a-afb47ad2eea5',
                'tag'        => 'Body Painting',
                'tag_safe'   => 'body-painting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'cc5eabb5-3f2c-41b5-b9b5-399a9b4d40ea',
                'tag'        => 'Arena',
                'tag_safe'   => 'arena',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b13ce7d5-d513-49ff-a957-76f193df42aa',
                'tag'        => 'Tournament',
                'tag_safe'   => 'tournament',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '57765528-fcd4-4942-95e5-c18ce13427f1',
                'tag'        => 'Baseball',
                'tag_safe'   => 'baseball',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f05f75ed-2e5e-4cb3-91c9-a50ed2e5896a',
                'tag'        => 'Traditional Dance',
                'tag_safe'   => 'traditional-dance',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '505e4b58-ad49-4c04-86a7-f7391cbf0b0a',
                'tag'        => 'G-Star',
                'tag_safe'   => 'g-star',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a4fac2cc-7cd4-44a6-b620-178182389a5b',
                'tag'        => 'Exploration',
                'tag_safe'   => 'exploration',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0c86fabf-317f-41e5-9eda-bd9880d70375',
                'tag'        => 'BlizzCon',
                'tag_safe'   => 'blizzcon',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '5788eae8-312d-43b5-a0b6-465eda087617',
                'tag'        => 'Glitched',
                'tag_safe'   => 'glitched',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '59389904-284b-4479-9d7d-e519d8fa8fb0',
                'tag'        => "Texas Hold'em",
                'tag_safe'   => 'texas-holdem',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '87461f91-8a5c-4233-92fd-38f321b8970d',
                'tag'        => 'Early Access Play',
                'tag_safe'   => 'early-access-play',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2dd8ed44-9043-4457-bb8d-e6c9a35e0b4d',
                'tag'        => 'Hair Styling',
                'tag_safe'   => 'hair-styling',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '860f0dc1-5d6b-4504-a3e2-eca15a1cb816',
                'tag'        => 'All Bosses',
                'tag_safe'   => 'all-bosses',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'df262ff6-74d1-415b-942c-d584d44426c4',
                'tag'        => 'Epic Level Characters',
                'tag_safe'   => 'epic-level-characters',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1eea2343-ca8e-4606-ab21-5c64e129f6db',
                'tag'        => 'Easy Mode',
                'tag_safe'   => 'easy-mode',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '74011d60-f364-4f56-ab7f-cde2662630dd',
                'tag'        => 'St. Jude',
                'tag_safe'   => 'st-jude',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2bc53bf2-3abb-42ec-949f-ca50f60d1022',
                'tag'        => 'High Score Attempts',
                'tag_safe'   => 'high-score-attempts',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '18f59f1f-993d-4f8a-b435-8129a84aab17',
                'tag'        => 'GameBlast',
                'tag_safe'   => 'gameblast',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2a14b52e-d459-4c92-be11-5d86b898f6b6',
                'tag'        => 'Squad Stream',
                'tag_safe'   => 'squad-stream',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '09bc088e-ba15-41dc-beab-17dbcb04c800',
                'tag'        => 'No Out of Bounds',
                'tag_safe'   => 'no-out-of-bounds',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '69e12d80-7199-4e0a-b6aa-f9b1dd058bc5',
                'tag'        => 'Warpless',
                'tag_safe'   => 'warpless',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '47d6503f-a62c-453d-8913-bbcbabeaac7f',
                'tag'        => 'One-Shot Adventure',
                'tag_safe'   => 'one-shot-adventure',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a716383e-a9ff-4531-be5f-e25cdd7585d8',
                'tag'        => 'Low%',
                'tag_safe'   => 'low',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b1650f8e-cf56-4e62-99e3-0142cfc7e081',
                'tag'        => 'Catalan',
                'tag_safe'   => 'catalan',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '27937cec-5cfc-4f56-b1d3-f6e1d67735e2',
                'tag'        => 'Achievement Hunting',
                'tag_safe'   => 'achievement-hunting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '07e2c57f-86d3-43c9-b008-b04bfc9acc9d',
                'tag'        => 'PAX',
                'tag_safe'   => 'pax',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '04c37d08-bdcb-42ed-a0c8-13191d2bce82',
                'tag'        => 'Mode: Save the World',
                'tag_safe'   => 'mode-save-the-world',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8315b8d6-9837-4218-9bc1-3c0a3e5bb41d',
                'tag'        => 'Balance Training',
                'tag_safe'   => 'balance-training',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '07a1b526-3725-4ba5-8c53-efaad4941fb9',
                'tag'        => 'Strength Training',
                'tag_safe'   => 'strength-training',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'ba3b69fe-899c-4518-ac46-707275e3eba1',
                'tag'        => 'Vietnamese',
                'tag_safe'   => 'vietnamese',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '068c541b-dc07-4d7f-a689-5578f90905a9',
                'tag'        => 'Game Awards',
                'tag_safe'   => 'game-awards',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f61b8fe6-d22b-4f0b-ac99-cd852bc1b0b9',
                'tag'        => 'gamescom',
                'tag_safe'   => 'gamescom',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '77a928f7-39da-4dad-9d81-3e6bd7a36e04',
                'tag'        => 'PB Attempts',
                'tag_safe'   => 'pb-attempts',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd27da25e-1ee2-4207-bb11-dd8d54fa29ec',
                'tag'        => 'E3',
                'tag_safe'   => 'e3',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd35073b8-0e52-4375-9f75-3dde0c567911',
                'tag'        => 'Persistent Campaign',
                'tag_safe'   => 'persistent-campaign',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '06291cf5-d4e1-4c16-afbd-bd4282416ebc',
                'tag'        => 'Worker Placement',
                'tag_safe'   => 'worker-placement',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c8b3c2eb-8e4b-478e-b4e7-4f01cc4dc34a',
                'tag'        => 'Dreamhack',
                'tag_safe'   => 'dreamhack',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '31866a92-269d-4df3-a2fb-58081bf97378',
                'tag'        => 'Baking',
                'tag_safe'   => 'baking',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd33671c6-d05b-44a6-a548-5d5930365882',
                'tag'        => 'No Major Glitches',
                'tag_safe'   => 'no-major-glitches',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd654ad53-a88a-4194-b3eb-ebb8654d17cf',
                'tag'        => 'Neutral Characters',
                'tag_safe'   => 'neutral-characters',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '423f9bc1-5b64-4355-8dfe-4d7466455ba2',
                'tag'        => 'Poker Mixed Games',
                'tag_safe'   => 'poker-mixed-games',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '73645e21-02ae-4f39-bfb1-8dac623927ef',
                'tag'        => 'Movement Training',
                'tag_safe'   => 'movement-training',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e56c8206-64ca-4e25-ae38-f3732f49599d',
                'tag'        => 'Nail Art',
                'tag_safe'   => 'nail-art',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3bbf3e11-717e-46af-aec3-37e4f9216db4',
                'tag'        => 'Deck Construction',
                'tag_safe'   => 'deck-construction',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd2e34e61-fbeb-4c70-9c98-474fce8df9e2',
                'tag'        => 'Dragon Con',
                'tag_safe'   => 'dragon-con',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c22bdbea-f4f9-40b4-9f01-bd6f702a37f8',
                'tag'        => 'Subscriber Stream',
                'tag_safe'   => 'subscriber-stream',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e62cb1d5-a47d-4690-a373-fe4c0856f78b',
                'tag'        => 'BMX',
                'tag_safe'   => 'bmx',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '77e70c59-d6f9-44e7-a68e-608ebc173dbb',
                'tag'        => 'Mode: Blackout',
                'tag_safe'   => 'mode-blackout',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1b70fcca-0579-446a-90d1-075c9ce62309',
                'tag'        => 'Magic Tricks',
                'tag_safe'   => 'magic-tricks',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '46a33c8e-d3c6-417b-bf77-2b43d74a9298',
                'tag'        => 'Stack Up',
                'tag_safe'   => 'stack-up',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '532af76e-eabd-451e-9709-cd1cc7653edb',
                'tag'        => 'Unmodded',
                'tag_safe'   => 'unmodded',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1942f267-26a3-4ee8-9aa0-48cc4aea988e',
                'tag'        => 'American Football',
                'tag_safe'   => 'american-football',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '1a88aebe-e136-45f7-946c-f118f7e2dc51',
                'tag'        => 'MMA',
                'tag_safe'   => 'mma',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c1ab2f2b-2065-47c9-9655-bb2cc280b7f1',
                'tag'        => 'Hockey',
                'tag_safe'   => 'hockey',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'b157e8d6-b7ba-49f4-836f-09886c072f1f',
                'tag'        => 'Extension Enhanced',
                'tag_safe'   => 'extension-enhanced',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a005b174-b20e-46b1-8679-4589fef81c8e',
                'tag'        => 'Match Commentary',
                'tag_safe'   => 'match-commentary',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a4c5e6a9-5164-4775-959e-06167dbfa2d0',
                'tag'        => 'Mode: Spectator',
                'tag_safe'   => 'mode-spectator',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '0e2fce97-3d1b-4cd0-bd04-b9f9e2907b91',
                'tag'        => 'Hidden Identity',
                'tag_safe'   => 'hidden-identity',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '708c1251-4550-486a-942f-a1dcaabb41c8',
                'tag'        => 'APAC Server',
                'tag_safe'   => 'apac-server',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '2a824c85-8c64-4a62-9532-84a50633c6fc',
                'tag'        => 'Hiking',
                'tag_safe'   => 'hiking',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '692af1d4-da0f-4b9b-889b-2579adc53765',
                'tag'        => 'Multi-Table Tournament',
                'tag_safe'   => 'multi-table-tournament',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'a7bd15ad-7d2b-4a4c-a7e9-e75a70b51e65',
                'tag'        => 'Area Control',
                'tag_safe'   => 'area-control',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '36a89a80-4fcd-4b74-b3d2-2c6fd9b30c95',
                'tag'        => 'Esports',
                'tag_safe'   => 'esports',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '3453ef8c-bc39-4811-8fb5-595e7b96fc47',
                'tag'        => 'Pacifist Run',
                'tag_safe'   => 'pacifist-run',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c8d6d6ee-3b02-4ae7-81e9-4c0f434941cc',
                'tag'        => 'Ludum Dare',
                'tag_safe'   => 'ludum-dare',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '7ddba84a-594d-4a3f-9136-1484ce243d43',
                'tag'        => 'Routing',
                'tag_safe'   => 'routing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c2542d6d-cd10-4532-919b-3d19f30a768b',
                'tag'        => 'Drops Enabled',
                'tag_safe'   => 'drops-enabled',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '8e44481a-4bc4-4155-b362-9bb499c15d3e',
                'tag'        => 'Surfing',
                'tag_safe'   => 'surfing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6cb33655-173e-464e-baf8-780db60500d5',
                'tag'        => 'Motorsports',
                'tag_safe'   => 'motorsports',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'f38aa362-e2c9-48eb-9a82-13eeb14d1d5a',
                'tag'        => 'Sport Talk',
                'tag_safe'   => 'sport-talk',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '864f2b86-b5d2-446d-bf3b-e1b34d3ca057',
                'tag'        => 'Sidecasting',
                'tag_safe'   => 'sidecasting',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'd5713b1e-c796-4bdc-88e2-93c49ce31136',
                'tag'        => 'Cycling',
                'tag_safe'   => 'cycling',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '9f3c36df-5b3c-4043-abbc-43c1dcd31047',
                'tag'        => 'Winter Sports',
                'tag_safe'   => 'winter-sports',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '617e45cb-1c58-43ef-b5f3-050dbd8ae7ca',
                'tag'        => 'Cricket',
                'tag_safe'   => 'cricket',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'e015369e-faab-4e36-a47f-e67ca4370715',
                'tag'        => 'Horse Racing',
                'tag_safe'   => 'horse-racing',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'c1997ef1-94bb-48e1-89db-f5e56e7aad2c',
                'tag'        => 'Golf',
                'tag_safe'   => 'golf',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '6f70af0e-2ac0-4939-9ec9-31a770ea1ed3',
                'tag'        => 'Twitch Rivals',
                'tag_safe'   => 'twitch-rivals',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '385590ed-7334-40b0-a24e-4ae83489bffc',
                'tag'        => 'Raquetball',
                'tag_safe'   => 'raquetball',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '35d13143-2a0b-42e0-8881-e4c73878c5a3',
                'tag'        => 'Gymnastics',
                'tag_safe'   => 'gymnastics',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => 'eb33ecc9-abb3-4775-95ce-08500b7d2dfa',
                'tag'        => 'Formula 1',
                'tag_safe'   => 'formula-1',
                'is_tag'     => true,
            ],
            [
                'tag_id'     => '7706b4a4-a582-4e85-9ad6-c4508687c278',
                'tag'        => 'Billiards',
                'tag_safe'   => 'billiards',
                'is_tag'     => true,
            ],
        ];

        collect($tags)
            ->each(function ($tag) {
                Tags::updateOrCreate([
                    'tag_safe'        => $tag['tag_safe'],
                ], Arr::except($tag, ['tag_safe']));
            });
    }
}
