replicaCount: 1
env: local
logChannel: stack
repositoryName: CreativeStreams
image:
  repository: creativestreams
  pullPolicy: IfNotPresent
  registry: senshudo
projectPath: ""
xdebugEnabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
    - name: web
      port: 80

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: traefik
  hosts:
    - name: creativestreams
      host: creativestreams.test
      paths: ["/"]
    - name: creativestreamswww
      host: www.creativestreams.test
      paths: ["/"]
    - name: creativestreamswaypoint
      host: waypoint.creativestreams.test
      paths: ["/"]

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
